### ISSUE TITLE
slow motion - can not change activeVideoMinFrameDuration, activeVideoMaxFrameDuration and videoFrameRate since lookForConfiguration always returns 0

### ISSUE THREAD

**Issue by manans25** [piemonte/PBJVision#127]
I tried changing the fps to 60, permissible by iPhone 5 and I see that  I cannot set the below since lockForConfiguration always returns 0.

Therefore, the below attributes cannot be set -
                _currentDevice.activeVideoMinFrameDuration = fps;
                _currentDevice.activeVideoMaxFrameDuration = fps;
                _videoFrameRate = videoFrameRate;

Calling lockForConfiguration, is not returning any errors. It always returns 0 or no for whether the lock was acquired or not. I don't know why it won't grant the lock. 
[device lockForConfiguration:nil];

**Comment by zipnadarien** [comment]
I'm actively using the high FPS so thought I'd pass on what I've uncovered and solutions - 

- In setVideoFrameRate: the device format has to be set with this line of code once the desired format is identified. Must be done before setting the FPS.

 _currentDevice.activeFormat = supportingFormat;

- as mentioned previously by somebody else, setting the frame rate also has to be done after the _currentDevice setup is complete. I change the frame rate in the visionSessionDidStartPreview method.

- Regardless of the target FPS, changing the deviceFormat from the default format causes AVAssetWriter to fail for any output format other than PBJOutputFormatWidescreen. I have more information on this, but too much to post. Essentially it's the dimensions of the sampleBuffer. I'm going to dig into this more.

- For my purposes I need to use the square setting, so I set up the AVAssetWriter video dimensions to 500 x 500 and then I can save frames.

- I'm recording at high FPS, but saving at _normal_ FPS so I've also modified writeSampleBuffer: to provide this. I create my own CMTime timestamp.

The net is, I'm capturing at 240 fps in a square format and saving at 30 fps. That's what I need.

- my app toggles between photo and video. When I toggle from photo to video the high FPS is reset (which is kind of expected). If I set the frame rate the app crashes - I suspect because of setting up the camera on one thread conflicting with toggling photo to video on the main thread. I'm going to dig into this so toggling photo/video doesn't screw up the desired frame rate.

**Comment by piemonte** [comment]
hey @zipnadarien thanks for the notes, much appreciated. if it's possible to share a [gist](https://gist.github.com) or a pull request with changes, that would be helpful.

**Comment by praveenaj** [comment]
@zipnadarien I'd really appreciate if you can make a gist out of our working code as @piemonte  mentioned :)

**Comment by piemonte** [comment]
:paperclip: https://github.com/piemonte/PBJVision/pull/235

**Comment by praveenaj** [comment]
@piemonte Thanks. Will check it out! :+1:

**Comment by georgel** [comment]
Hi, just want to confirm that this works. I am now capturing at 120 fps and doing some interesting effects with it. However, I am stuck with the output format set to widescreen. I assume this is related to the buffer issue mentioned by @zipnadarien.  

Can any of your experts give me a hint as to the best way to get portrait and square format video to work with this?  I am happy to make it work myself. But can sure use some clues hehe :)

**Comment by piemonte** [comment]
Hey @georgel are you setting the output format property to square?

https://github.com/piemonte/PBJVision/blob/master/Source/PBJVision.h#L162
