### ISSUE TITLE
How capture slow-mo with PBJVision ?

### ISSUE THREAD

**Issue by Briahas** [piemonte/PBJVision#334]
How capture slow-mo with PBJVision ?

**Comment by Briahas** [comment]
any info?

**Comment by jayendra462** [comment]
@Briahas can you get anything ?? related to slow motion ??

**Comment by jayendra462** [comment]
i need your help for capturing slow motion video. using PBJVision

**Comment by ar-labs-tech** [comment]
Need help for capturing slow-motion video using PBJVision can I have a sample code for that. because I didn't get anything. I'm set video framerate 120fps.

videoFrameRate = 120

_currentDevice.activeVideoMinFrameDuration = fps;
_currentDevice.activeVideoMaxFrameDuration = fps;

when I save the video and play it normally. 
Can you help me @piemonte to send sample demo for slow-motion video. 
FYI : my device is supported 120 and 240 fps.

Thanks in advance.
